apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sumanthportfolio

resources:
  - namespace.yaml
  - api_deployment.yaml
  - api_service.yaml
  - web_deployment.yaml
  - web_service.yaml
  - ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/name: portfolio-app
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: true

images:
  - name: sumanthportfolio-api
    newTag: local
  - name: my-portfolio-web
    newTag: local

secretGenerator:
  - name: portfolio-secrets
    envs:
      - .env.secrets.local
    type: Opaque

configMapGenerator:
  - name: portfolio-configmap
    envs:
      - .env.configmap